services:
  spintheweb:
    image: spintheweb:dev
    build:
      context: .
    container_name: spintheweb
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      # Set your portal endpoint. Example: https://example.com/webapplication.wbdl
      # This can also be provided via environment when running docker compose
      # e.g., `PORTAL_URL=https://... docker compose up`
      - PORTAL_URL
    expose:
      - "8080"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - spintheweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: