services:
  spintheweb:
    image: spintheweb:dev
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: spintheweb
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      # Set your portal endpoint. Example: https://example.com/webapplication.wbdl
      # This can also be provided via environment when running docker compose
      # e.g., `PORTAL_URL=https://... docker compose up`
      - PORTAL_URL
    expose:
      - "8080"
    restart: unless-stopped
    depends_on:
      - mysql

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - spintheweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # Domain Caddy should serve. Example: sandbox.spintheweb.org
      - SITE_DOMAIN=${SITE_DOMAIN}
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: webspinner_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=change_me_root_password
      - MYSQL_DATABASE=webspinner
      - MYSQL_USER=webspinner
      - MYSQL_PASSWORD=webspinner_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

volumes:
  caddy_data:
  caddy_config:
